# Geodetic motion in Schwarzschild geometry

### The metric and the geodesic equation

The metric of the Schwarzschild space around a not charged, not spinnig black hole is $$ ds^2 = -(1-\frac{2GM}{r})c^2 dt^2 +(1-\frac{2GM}{r})^{-1} dr^2 + r^2 d\theta^2 + r^2 \sin(\theta)^2 d\phi^2 $$ 
The metric is described by $ g_{\mu \nu} = diag(-(1-\frac{2GM}{r}), (1-\frac{2GM}{r})^{-1}, r^2, r^2\sin(\theta)^2) $ 
 
The evolution of a massive body in geodesic motion is described by
$$ \begin{equation}
    \begin{cases}
      \frac{dx^\mu}{d \tau}= u^\mu\\
      \frac{du^\alpha}{d \tau} + \Gamma^\alpha_{\beta \gamma}u^\beta u^\gamma = 0
    \end{cases}\
\end{equation} $$
The equation can be integrated in the proper time to obtain the coordinate time and the position of the body $ x^\mu = (t, r, \theta, \phi) $ 
 
  
The non-zero Christoffel symbols are 

$$ \begin{matrix}
 \Gamma^r_{tt}= \frac{GM(r-2GM)}{r^3}  &  \Gamma^r_{\phi\phi}= -(r-2GM)\sin2\theta  &   \Gamma^r_{\theta\theta}= -(r-2GM)  \\
 \Gamma^r_{rr}= -GMr(r-2GM)  &  \Gamma^t_{rt}= \frac{GM}{r(r-2GM)}  &   \Gamma^\theta_{\phi\phi}= -\sin\theta\cos\theta  \\
 \Gamma^\phi_{r\phi}= \frac{1}{r}  &   \Gamma^\theta_{r\theta}= \frac{1}{r}  &   \Gamma^\phi_{\theta\phi}=\sin\theta\cos\theta 
\end{matrix} $$

In [46]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as ani
import pandas as pd
from scipy.integrate import solve_ivp

In [47]:

G = 6.6743e-11
M = 1.98847e30
c = 299792458

R_s = (G*M)/c**2  #Schwarzschild radius in meters

print(f'The Schwarzschild radius of the system is {R_s:.4e} m')
G, c, M = 1, 1, 1


The Schwarzschild radius of the system is 1.4767e+03 m


### Definitions of the metric and the Christoffel symbols

In [48]:
# The metric depends on the point where it is calculated

g = lambda x: np.diag([-(1-2*G*M/x[1]),(1-2*G*M/x[1])**-1, x[1]**2, (x[1]*np.sin(x[2]))**2])

# Christoffel symbols

def Chr(x):
  r, theta = x[1], x[2]
  ch = np.zeros((4,4,4))
  ch[1][0][0] = G*M*(r-2*G*M)/r**3      # r-tt
  ch[0][1][0] = G*M/(r*(r-2*G*M))    # t-rt
  ch[0][0][1] = G*M/(r*(r-2*G*M))    # t-tr
  
  ch[1][1][1] = -G*M/(r*(r-2*G*M))    # r-rr
  
  ch[1][2][2] = -(r-2*G*M)     # r-theta theta
  ch[2][1][2] = -(r-2*G*M)     # theta - r theta
  ch[2][2][1] = -(r-2*G*M)     # theta - theta r
  
  ch[1][3][3] = -(r-2*G*M)*np.sin(2*theta)    # r- phi phi
  ch[3][1][3] = 1/r    # phi- r phi
  ch[3][3][1] = 1/r    # phi- phi r
  
  ch[2][3][3] = -0.5*np.sin(2*theta)   # theta - phi phi
  ch[3][2][3] = 0.5*np.sin(2*theta)   # phi - theta phi
  ch[3][3][2] = 0.5*np.sin(2*theta)   # phi - phi theta
  
  return ch

def dot(a,b,x):
  return np.dot(a,np.dot(g(x), b))

In [55]:
a = np.array([1,0,0,1])
b = np.array([1,1,0,1])
x = np.array([0,10,0.6,0])
print(Chr(x))

[[[ 0.          0.0125      0.          0.        ]
  [ 0.0125      0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.        ]]

 [[ 0.008       0.          0.          0.        ]
  [ 0.         -0.0125      0.          0.        ]
  [ 0.          0.         -8.          0.        ]
  [ 0.          0.          0.         -7.45631269]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.         -8.          0.        ]
  [ 0.         -8.          0.          0.        ]
  [ 0.          0.          0.         -0.46601954]]

 [[ 0.          0.          0.          0.        ]
  [ 0.          0.          0.          0.1       ]
  [ 0.          0.          0.          0.46601954]
  [ 0.          0.1         0.46601954  0.        ]]]
